# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Eugine Caroline Shin
tagline:          'Ph.D. Student'
description:      'Ph.D. Student @tOSU'
url:              http://carolineugine.github.io
baseurl:          
logo:             /assets/images/picture.png

author:
  name:           'Eugine Shin'
  # url:            https://twitter.com/mdo

# gems:  [jekyll-paginate]
# paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-gist